version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: spreetrail-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: spreetrail
      POSTGRES_PASSWORD: spreetrailpassword
      POSTGRES_DB: spreetrail_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
